### ISSUE TITLE
框架无法支持现有的CQHTTP 反向WebSocket协议

### ISSUE THREAD

**Issue by CBGan** [frank-bots/cqhttp.Cyan#19]
平台：[Mirai](https://github.com/mamoe/mirai)
CQHTTP插件：[cqhttp-mirai](https://github.com/yyuueexxiinngg/cqhttp-mirai)
可以考虑下适配吗(微弱)

**Comment by frankli0324** [comment]
好的，这两天在考试。。等大概一个礼拜？

**Comment by CBGan** [comment]
嘛我也不急2333
加油考试吧

**Comment by yyuueexxiinngg** [comment]
确认为`cqhttp-mirai`方的问题 https://github.com/yyuueexxiinngg/cqhttp-mirai/issues/69

**Comment by frankli0324** [comment]
thanks
