### ISSUE TITLE
群组信息不全

### ISSUE THREAD

**Issue by Caulm** [frank-bots/cqhttp.Cyan#25]
版本：
go-cqhttp v1.0.0-beta6
cqhttp.Cyan 3.1.0

我想做一个只允许群主和管理员使用的指令，取`client.group_table`的时候发现好像每个群的信息只有bot自己，没有其他成员？我已经打开了`use_group_table`

```C#
string accessUrl = "ws://127.0.0.1:6700";
string accessToken = "1234567890";
string eventUrl = "ws://127.0.0.1:6700/event/";
CQApiClient client = new CQWebsocketClient(accessUrl, accessToken, eventUrl, true);
```

![image](https://user-images.githubusercontent.com/40651411/134049139-2cf9b7e3-c191-4a87-babe-f76eb5708497.png)

**Comment by frankli0324** [comment]
group_table会在调用`GetGroupMemberListRequest`后缓存结果，但不会主动调用此API，抱歉文档里没写清楚。。当时的考虑我记得是在一些大型群组中使用时自动调用此API可能数据量过大。这玩意也就是为了让bot能少调用几次API
![image](https://user-images.githubusercontent.com/20221896/134101902-ad4a7b53-8888-4b36-9860-a512be3fce06.png)
然后由于每次收到群组消息时会调用`GetGroupMemberInfoRequest`获取自身在群组中的信息赋给`GroupMessageEvent`的`self_info`，所以会缓存自身的信息。
你可以这样写：

```csharp
client.OnEventAsync += async (c, e) => {
    switch (e) {
    case GroupMessageEvent me:
        if (c.group_table[me.group_id].Count == 1)
            await c.SendRequestAsync (new GetGroupMemberListRequest (me.group_id));
        Console.WriteLine ($"in group: {me.group_id}");
        Console.WriteLine (string.Join (Environment.NewLine, c.group_table[me.group_id]));
        break;
    }
    return new EmptyResponse ();
};
```

**Comment by Caulm** [comment]
可以了！谢谢大佬
