### ISSUE TITLE
你好，请教一下！

### ISSUE THREAD

**Issue by andytree** [frank-bots/cqhttp.Cyan#4]
我想使用WPF写一个QQ机器人的控制端，但是在WPF界面和websocket结合使用这里卡住了，你的Cyan的websocket是否可以直接和WPF结合呢，因为我才看C#，不太清楚，所以希望您可以指导一下，希望可以能收到您指导性建议！感谢
另外，可以给我你的QQ或者Cyan的交流群吗？我想加入学习和交流下。感谢。

**Comment by frankli0324** [comment]
恩。。。我记得dotnet core3就会加入WPF支持了

**Comment by frankli0324** [comment]
https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/

**Comment by frankli0324** [comment]
再等等？

**Comment by andytree** [comment]
可以给我一个QQ联系方式吗？C#我刚接触，使用偶尔可能有问题想请教下。Cyan能组织一个QQ交流群吗？比如cqhttpapi和nonebot也是这样的，如果大家有好的想法也可以贡献出来呢。




------------------ 原始邮件 ------------------
发件人: "Frank"<notifications@github.com>; 
发送时间: 2019年4月19日(星期五) 中午11:32
收件人: "frank-bots/cqhttp.Cyan"<cqhttp.Cyan@noreply.github.com>; 
抄送: "Big_Tree"<632622435@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [frank-bots/cqhttp.Cyan] 你好，请教一下！ (#4)




https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/
 
&mdash;

**Comment by frankli0324** [comment]
我没用websocketsharp是因为当时写的时候（不知道现在如何了）它好像还没有较好地支持dotnet core

**Comment by andytree** [comment]
收到，感谢，.net core和.net Framework我都还没搞清是什么关系，是不是目前您写的Cyan，还不支持WPF的意思吗？




------------------ 原始邮件 ------------------
发件人: "Frank"<notifications@github.com>; 
发送时间: 2019年4月19日(星期五) 中午11:32
收件人: "frank-bots/cqhttp.Cyan"<cqhttp.Cyan@noreply.github.com>; 
抄送: "Big_Tree"<632622435@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [frank-bots/cqhttp.Cyan] 你好，请教一下！ (#4)




https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/
 
&mdash;

**Comment by frankli0324** [comment]
QQ加你了

**Comment by frankli0324** [comment]
。。。QQ上给你说话加你好友没反应。。？

**Comment by frankli0324** [comment]
。。。。。。。。。。
