### ISSUE TITLE
希望新增反向WS功能。

### ISSUE THREAD

**Issue by andytree** [frank-bots/cqhttp.Cyan#5]
所有客户端自动上报到同一个websocket server地址，server为每个酷Q分配一个session，session通过self_id(QQ号)来辨别。
这样server可以监控所有server的message，notice等等。然后来根据notice或者message来实现不一样的业务逻辑。
目前CQHTTPAPI的桌子写的NoneBot框架就和这个比较类似。
https://github.com/richardchien/nonebot

概览 | NoneBot https://none.rclab.tk/guide/
可以借鉴下！

**Comment by frankli0324** [comment]
* 反向websocket已经实现，可以走CQReverseWSClient。目前主要存在的问题是写的时候没有考虑监听上报和调用API绑定到同一地址的情况，之后会再想办法
* nonebot严格来说并不算SDK，其依赖aiocqhttp，本项目大体上等价于aiocqhttp，之后可能会将EssentialBot逐步完善为nonebot等价物
暂时先close了。。。
