### ISSUE TITLE
关于信息获取的一些问题

### ISSUE THREAD

**Issue by Reshirem** [frank-bots/cqhttp.Cyan#6]
想问一下，cyan能不能在获取message的同时，获取这message所在群组里，同时识别自己有没有绿帽子。我翻了一下api貌似没有看到。

**Comment by frankli0324** [comment]
很常用么？
很常用的话放假的时候我整一下  

* 若消息来源为群组，若开启了群员列表缓存，则从缓存中读取自己的身份（管理员/群主/群员）写入GroupMessage的属性  

这两天期末考试  
大雾杀我

**Comment by Reshirem** [comment]
@frankli0324 比如，我设置一个禁言抽奖，没有识别的话，没有绿帽的群也能运行，就不够智能。
应该还有其他需要的地方吧。
反正我是希望能有这么一个识别owo

**Comment by frankli0324** [comment]
https://github.com/frank-bots/cqhttp.Cyan/commit/5abf7ae43c54735ff65b0af32545a335fe81916a

**Comment by frankli0324** [comment]
dbq，GroupTable貌似之前有问题，已修复
启用group_table示意:
```csharp
var client = new CQHTTPClient (
    access_url: "",
    use_group_table: true
);
```

**Comment by Reshirem** [comment]
@frankli0324 收到w，感想~
