### ISSUE TITLE
bface 报错

### ISSUE THREAD

**Issue by Gaia-X-Alter** [frank-bots/cqhttp.Cyan#7]
BuildElement->bface
一接收到任何原创表情就会出现 System.FormatException:“Input string was not in a correct format.”
麻烦修复下

**Comment by frankli0324** [comment]
危
其实是修了的（恐慌
https://github.com/frank-bots/cqhttp.Cyan/commit/20122e2c45db2655b8e9534dcc08429a4abbb5db
让我去推到仓库里头。。。
