### ISSUE TITLE
求教,有没有办法同时回应两次对话

### ISSUE THREAD

**Issue by Gaia-X-Alter** [frank-bots/cqhttp.Cyan#8]
如果两个await的话,有的时候只回应一次对话

**Comment by Gaia-X-Alter** [comment]
看了下,其实不是await的锅,找了报错
System.InvalidOperationException: There is already one outstanding 'ReceiveAsync' call for this WebSocket instance. ReceiveAsync and SendAsync can be called simultaneously, but at most one outstanding operation for each of them is allowed at the same time.

**Comment by Gaia-X-Alter** [comment]
跪求QQ群讨论

**Comment by frankli0324** [comment]
emmmmm
我想想办法。。。

**Comment by frankli0324** [comment]
这两天有期中考试，过两天整嗷

**Comment by frankli0324** [comment]
TODO: 为WebSocket连接方式添加连接池

**Comment by Gaia-X-Alter** [comment]
> TODO: 为WebSocket连接方式添加连接池

我用http 了(小声

**Comment by frankli0324** [comment]
。算是。。解决了吧
