### ISSUE TITLE
client.alive 返回 False，但是 qq 号和昵称可以正常获取

### ISSUE THREAD

**Issue by FETE-CH** [frank-bots/cqhttp.Cyan#9]
client.alive 返回 False，消息列表和群组列表也都返回 null，无法正常操作。这是什么原因？

- 操作系统：Windows 10 1903
- 运行环境：.net core 3.0
- 酷Q： Air 版 5.15.3A(191014)
- 插件：coolq-http-api v4.12.2

**Comment by FETE-CH** [comment]
急，急，急！！！跪求讨论群😭

**Comment by frankli0324** [comment]
对不起，下周二我期中考试考完再解决可以么。。。ORZ

**Comment by FETE-CH** [comment]
那先备考吧，麻烦你了

**Comment by frankli0324** [comment]
嗷。。。我看了眼，是这样
判断alive的逻辑我没太仔细写，随便照着MetaEvent的返回值进行的判定
也就是说，如果cqhttp那边没有配置[heartbeat](https://cqhttp.cc/docs/4.12/#/Post?id=%E5%BF%83%E8%B7%B3)或者使用了[非http连接方式](https://cqhttp.cc/docs/4.12/#/Post?id=%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F)，我这个收不到MetaEvent，就不会去更新alive的值emmm。。。
我待会大概会完善一下alive判定逻辑，我先吃个饭（（

**Comment by FETE-CH** [comment]
但是，`client.groupTable` 和 `client.messageTable` 的值都为 null，是不能这样获取吗？

**Comment by frankli0324** [comment]
你需要在构造函数里头
use_grouptable: true
use_messagetable: true

**Comment by frankli0324** [comment]
。。我的锅我没说清楚za咋用
![image](https://user-images.githubusercontent.com/20221896/67912635-87623480-fbc5-11e9-9d34-af56defcfcff.png)
